export const charityData = [
    {
        name: "Антон",
        id: "111-1",
        age: 9,
        sex: "male",
        wish: "набір для творчості «Машина»",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-1.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Богдан",
        id: "111-2",
        age: 15,
        sex: "male",
        wish: "набір для випалювання на фанері",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-2.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Валентин",
        id: "111-3",
        age: 11,
        sex: "male",
        wish: "набір «Моделі з фанери»",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-3.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Валерія",
        id: "111-4",
        age: 10,
        sex: "female",
        wish: "набір «Художня вишивка» ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-4.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Ваня",
        id: "111-5",
        age: 6,
        sex: "male",
        wish: "набір для творчості «Лото для малювання»  ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-5.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Віталік",
        id: "111-6",
        age: 12,
        sex: "male",
        wish: "конструктор металевий",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-6.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Володимир",
        id: "111-7",
        age: 6,
        sex: "male",
        wish: "набір для творчості «Дитячий будинок» ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-7.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Дар'я",
        id: "111-8",
        age: 13,
        sex: "female",
        wish: "набір «Алмазна мозаїка»",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-8.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Денис",
        id: "111-9",
        age: 10,
        sex: "male",
        wish: "набір «Досліди»",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-9.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Денис",
        id: "111-10",
        age: 12,
        sex: "male",
        wish: "набір для створення свічок з кольорової вощини",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-10.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Діана",
        id: "111-11",
        age: 8,
        sex: "female",
        wish: "набір для творчості «Містер тісто» ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-11.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Дмитро",
        id: "111-12",
        age: 14,
        sex: "male",
        wish: "набір «Алмазна мозаїка» ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-12.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Злата",
        id: "111-13",
        age: 4,
        sex: "female",
        wish: "розмальовка для дівчат ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-13.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Каріна",
        id: "111-14",
        age: 10,
        sex: "female",
        wish: "набір «Декоративна писанка» ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-14.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Катерина ",
        id: "111-15",
        age: 11,
        sex: "female",
        wish: "мозаїка",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-15.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Лєра",
        id: "111-16",
        age: 17,
        sex: "female",
        wish: "картина «Вишивка бісером»",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-16.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Максим",
        id: "111-17",
        age: 11,
        sex: "male",
        wish: "конструктор",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-17.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Настя",
        id: "111-18",
        age: 14,
        sex: "female",
        wish: "набір «Бісероплетіння» ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-18.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Наташа",
        id: "111-19",
        age: 9,
        sex: "female",
        wish: "набори «Квілінг» та  «Бісер» ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-19.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Оксана ",
        id: "111-20",
        age: 12,
        sex: "female",
        wish: "набір «Алмазна мозаїка»",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-20.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Павло",
        id: "111-21",
        age: 10,
        sex: "male",
        wish: "набір «Моделі з фанери» ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-21.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Саша",
        id: "111-22",
        age: 8,
        sex: "male",
        wish: "набір для творчості  «Кінетичний пісок для творчості»",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-22.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Сергій",
        id: "111-23",
        age: 13,
        sex: "male",
        wish: "набір «Моделі з фанери» ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-23.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Сніжана",
        id: "111-24",
        age: 9,
        sex: "female",
        wish: "набір для творчості «Маленький гончар» автоматичний",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-24.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Софія",
        id: "111-25",
        age: 9,
        sex: "female",
        wish: "Адвент-календар",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-25.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Тамара ",
        id: "111-26",
        age: 15,
        sex: "female",
        wish: "картина малювання  за номерами",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-26.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Таня",
        id: "111-27",
        age: 15,
        sex: "female",
        wish: "картина малювання за номерам",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-27.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Юра",
        id: "111-28",
        age: 6,
        sex: "male",
        wish: "«Розмальовка для малюків» ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-28.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Юрій",
        id: "111-29",
        age: 7,
        sex: "male",
        wish: "набір для творчості з фарбами «Заміський  будинок із ХДФ»  ",
        orphanаge: "Вінницький обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/111-29.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Богом`я Роман",
        id: "333-1",
        age: 12,
        sex: "male",
        wish: "баф і перчатки спортивні",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-1.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Бондаренко Максим",
        id: "333-2",
        age: 6,
        sex: "male",
        wish: "іграшка-робот",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-2.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Донський-Гуменний Владислав",
        id: "333-3",
        age: 13,
        sex: "male",
        wish: "кружка з персонажем з фільму",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-3.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Говорун Влада",
        id: "333-4",
        age: 14,
        sex: "female",
        wish: "одяг",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-4.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Дерев`янко Женя",
        id: "333-5",
        age: 14,
        sex: "female",
        wish: "гумки для плетіння",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-5.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Зінченко Злата",
        id: "333-6",
        age: 9,
        sex: "female",
        wish: "теплий костюм та кросівки",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-6.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Зінченко Саша",
        id: "333-7",
        age: 9,
        sex: "female",
        wish: "блокнот, ведмедик та пенал",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-7.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Калітвінцев Андрій",
        id: "333-8",
        age: 13,
        sex: "male",
        wish: "кружка з персонажем з фільму",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-8.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Катулін Сергій",
        id: "333-9",
        age: 6,
        sex: "male",
        wish: "ігровий військовий гелікоптер",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-9.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Катуліна Наташа",
        id: "333-10",
        age: 3,
        sex: "female",
        wish: "лялька з коляскою",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-10.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Крамаренко Діма",
        id: "333-11",
        age: 12,
        sex: "male",
        wish: "футбольний м'яч",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-11.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Крамаренко Олеся",
        id: "333-12",
        age: 14,
        sex: "female",
        wish: "одяг",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-12.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Лазаренко Альона",
        id: "333-13",
        age: 7,
        sex: "female",
        wish: "картина за номерами",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-13.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Овчарик Діма",
        id: "333-14",
        age: 11,
        sex: "male",
        wish: "пожежна машинка і червоний светр",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-14.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Пархоменко Артур",
        id: "333-15",
        age: 7,
        sex: "male",
        wish: "солодощі",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-15.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Поп Ліана",
        id: "333-16",
        age: 8,
        sex: "female",
        wish: "лялька з розкішним волоссям",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-16.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Псюрніченко Мирослав",
        id: "333-17",
        age: 16,
        sex: "male",
        wish: "баф і перчатки спортивні",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-17.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Псюрніченко Родіон",
        id: "333-18",
        age: 16,
        sex: "male",
        wish: "фірмові рукавиці та шкарпетки",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-18.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Січкар Оленка",
        id: "333-19",
        age: 5,
        sex: "female",
        wish: "сукня золотавого кольору",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-19.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Степнова Кароліна",
        id: "333-20",
        age: 9,
        sex: "female",
        wish: "м'яка іграшка-каченятко",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-20.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Торганенко Вітя",
        id: "333-21",
        age: 8,
        sex: "male",
        wish: "конструктор Lego",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-21.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Шаповал Єва",
        id: "333-22",
        age: 4,
        sex: "female",
        wish: "лялька",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-22.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Шаповал Софія",
        id: "333-23",
        age: 4,
        sex: "female",
        wish: "ведмедик-панда",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-23.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Шевченко Люда",
        id: "333-24",
        age: 13,
        sex: "female",
        wish: "набір сережки + кулон \"Ангел із серцем\"",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-24.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Юдченко Єгор",
        id: "333-25",
        age: 16,
        sex: "male",
        wish: "кросівки (43 р.)",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-25.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Юдченко Софія",
        id: "333-26",
        age: 14,
        sex: "female",
        wish: "косметика",
        orphanаge: "Черкаський обласний центр соціально-психологічної реабілітації дітей",
        letterUrl: "https://charity.team-911.com.ua/img/333-26.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Акопян Артем",
        id: "222-1",
        age: 15,
        sex: "male",
        wish: "пісочниця з кінетичним піском і солодощі",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-1.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Балах Ангеліна",
        id: "222-2",
        age: 9,
        sex: "female",
        wish: "пупс-сміхотун",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-2.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Барлет Олег",
        id: "222-3",
        age: 10,
        sex: "male",
        wish: "Лего та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-3.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Большакова Маргарита",
        id: "222-4",
        age: 10,
        sex: "female",
        wish: "магнітний конструктор та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-4.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Буяков Богдан",
        id: "222-5",
        age: 12,
        sex: "male",
        wish: "футбольний м'яч",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-5.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Гринчишина Ліза",
        id: "222-6",
        age: 9,
        sex: "female",
        wish: "музична абетка і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-6.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Гріщенко Максим",
        id: "222-7",
        age: 15,
        sex: "male",
        wish: "Лего \"Ніндзяго\"",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-7.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Дерябін Єгор",
        id: "222-8",
        age: 9,
        sex: "male",
        wish: "конструктор",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-8.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Ємченко Женя",
        id: "222-9",
        age: 9,
        sex: "female",
        wish: "ляльковий будиночок і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-9.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Єрошевич Даша",
        id: "222-10",
        age: 13,
        sex: "female",
        wish: "іграшковий телефон",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-10.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Желудченко Михайло",
        id: "222-11",
        age: 14,
        sex: "male",
        wish: "набір для сортування предметів, палички Кюізнера та солодощі",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-11.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Зимогляд Владислав",
        id: "222-12",
        age: 8,
        sex: "male",
        wish: "іграшка для розвитку",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-12.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Зубко Тетяна",
        id: "222-13",
        age: 13,
        sex: "female",
        wish: "картина за номерами і розфарбовки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-13.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Карабанова Люба",
        id: "222-14",
        age: 13,
        sex: "female",
        wish: "парфуми",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-14.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Карабанова Ольга",
        id: "222-15",
        age: 12,
        sex: "female",
        wish: "желейний бокс",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-15.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Катаріна Микита",
        id: "222-16",
        age: 9,
        sex: "male",
        wish: "машинка на радіоуправлінні та смаколики",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-16.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Козюк Петро",
        id: "222-17",
        age: 8,
        sex: "male",
        wish: "іграшковий робот і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-17.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Кондратюк Аліна",
        id: "222-18",
        age: 12,
        sex: "female",
        wish: "набір парфумів і солодощі",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-18.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Куріленко Максим",
        id: "222-19",
        age: 17,
        sex: "male",
        wish: "фломастери",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-19.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Кучеренко Кіра",
        id: "222-20",
        age: 7,
        sex: "female",
        wish: "велика мозаїка і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-20.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Легін Ілона",
        id: "222-21",
        age: 7,
        sex: "female",
        wish: "головоломка \"4 кольори\"",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-21.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Легін Кирило",
        id: "222-22",
        age: 13,
        sex: "male",
        wish: "будівельний конструктор",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-22.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Луконцев Ілля",
        id: "222-23",
        age: 10,
        sex: "male",
        wish: "іграшкова залізниця",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-23.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Любінецька Альона",
        id: "222-24",
        age: 15,
        sex: "female",
        wish: "м'яка іграшка і плед",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-24.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Любінецька Леся",
        id: "222-25",
        age: 16,
        sex: "female",
        wish: "теплий шарф і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-25.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Макаревич Софія",
        id: "222-26",
        age: 9,
        sex: "female",
        wish: "набір \"Монтессорі\"",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-26.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Макогоненко Стас",
        id: "222-27",
        age: 13,
        sex: "male",
        wish: "безпроводові навушники та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-27.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Марин Іван",
        id: "222-28",
        age: 11,
        sex: "male",
        wish: "іграшка \"Музичний Дід Мороз\" і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-28.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Марченко Андрій",
        id: "222-29",
        age: 16,
        sex: "male",
        wish: "навушники та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-29.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Міхальов Андрій",
        id: "222-30",
        age: 9,
        sex: "male",
        wish: "розмальовки, пластилін та пазли",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-30.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Мішалова Ліза",
        id: "222-31",
        age: 7,
        sex: "female",
        wish: "інтерактивна абетка",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-31.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Могукало Михайло",
        id: "222-32",
        age: 8,
        sex: "male",
        wish: "пірамідка-пасочка",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-32.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Москаль Артем",
        id: "222-33",
        age: 15,
        sex: "male",
        wish: "навушники",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-33.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Пагарєлий Влад",
        id: "222-34",
        age: 12,
        sex: "male",
        wish: "чашка, розмальовка та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-34.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Пержу Артем",
        id: "222-35",
        age: 6,
        sex: "male",
        wish: "літачок на управлінні",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-35.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Проскурня Катерина",
        id: "222-36",
        age: 16,
        sex: "female",
        wish: "диск здоров'я (тренажер)",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-36.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Рудь Марія",
        id: "222-37",
        age: 15,
        sex: "female",
        wish: "маленький фен та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-37.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Садовенко Дмитро",
        id: "222-38",
        age: 6,
        sex: "male",
        wish: "набір для малювання",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-38.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Самодін Владислав",
        id: "222-39",
        age: 16,
        sex: "male",
        wish: "навушники до телефону і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-39.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Сачук Діана",
        id: "222-40",
        age: 17,
        sex: "female",
        wish: "блютуз-колонка",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-40.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Семенів Валерій",
        id: "222-41",
        age: 11,
        sex: "male",
        wish: "набір з пластиліном, мозаїку та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-41.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Сентіщев Станіслав",
        id: "222-42",
        age: 10,
        sex: "male",
        wish: "літачок на управлінні",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-42.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Сидора Ангеліна",
        id: "222-43",
        age: 11,
        sex: "female",
        wish: "алмазна мозаїка та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-43.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Сидора Кирило",
        id: "222-44",
        age: 9,
        sex: "male",
        wish: "конструктор лего і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-44.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Скуменко Роман",
        id: "222-45",
        age: 8,
        sex: "male",
        wish: "пазли та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-45.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Снігова Єліна",
        id: "222-46",
        age: 16,
        sex: "female",
        wish: "алмазна мозаїка та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-46.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Тимошенко Софія",
        id: "222-47",
        age: 12,
        sex: "female",
        wish: "картина за номерами і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-47.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Ткаченко Софія",
        id: "222-48",
        age: 10,
        sex: "female",
        wish: "набір для бісероплетіння та лялька",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-48.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Трехманенко Аліна",
        id: "222-49",
        age: 16,
        sex: "female",
        wish: "солодощі",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-49.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Турлюн Денис",
        id: "222-50",
        age: 10,
        sex: "male",
        wish: "картина за номерами",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-50.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Фоменко Андріан",
        id: "222-51",
        age: 6,
        sex: "male",
        wish: "інтерактивний плакат \"Букварик\"",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-51.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Харитонов Віктор",
        id: "222-52",
        age: 10,
        sex: "male",
        wish: "паровозик",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-52.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Ходакевич Федір",
        id: "222-53",
        age: 12,
        sex: "male",
        wish: "пазли та фломастери",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-53.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Чорномор Гордій",
        id: "222-54",
        age: 8,
        sex: "male",
        wish: "повітряний пластилін, лото \"Світ навколо\" і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-54.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Шахман Дар'я",
        id: "222-55",
        age: 11,
        sex: "female",
        wish: "картина за номерами і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-55.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Шозда Дмитро",
        id: "222-56",
        age: 12,
        sex: "male",
        wish: "Лего та цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-56.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Шпартько Олександр",
        id: "222-57",
        age: 8,
        sex: "male",
        wish: "набір спортивних еспандерів",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-57.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Ющишина Марія",
        id: "222-58",
        age: 6,
        sex: "female",
        wish: "лялька \"Лол\" і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-58.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Ярош Артем",
        id: "222-59",
        age: 13,
        sex: "male",
        wish: "мозаїка, машинка-трансформер і солодощі",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-59.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    },
    {
        name: "Ященко Аліна",
        id: "222-60",
        age: 13,
        sex: "female",
        wish: "навушники і цукерки",
        orphanаge: "Знам'янська спеціальна загальноосвітня школа-інтернат",
        letterUrl: "https://charity.team-911.com.ua/img/222-60.jpg",
        wizard: null,
        wizardPhone: null,
        wizardMail: null,
        isSent: null
    }
];